import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile, mkdtemp, rm, writeFile, stat } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { parseManifest, normalizeGtin, digitalLink, classify, auditPages, reportCsv, escapeHtml, LIMITS } from '../docs/core.mjs';
import { runAudit, checkInputs } from '../docs/engine.mjs';
import { packetFiles, packetZip } from '../docs/packet.mjs';
import { adapter } from '../bin/node-adapter.mjs';
const A = '09506000134352', B = '09506000134369', header = 'file,page,sku,gtin,linear_count,link_count,link_host\n';
const csv = (name = 'proof.png', gtin = A, linear = 1, link = 1, host = 'id.example.com') => header + `${name},1,SKU-A,${gtin},${linear},${link},${host}\n`;
const file = async path => ({ name: path.split('/').at(-1), bytes: new Uint8Array(await readFile(new URL(path, import.meta.url))) });
const demoManifest = await readFile(new URL('../docs/samples/approved.csv', import.meta.url), 'utf8'), demoFile = await file('../docs/samples/proofs.pdf');
const truth = JSON.parse(await readFile(new URL('fixture-truth.json', import.meta.url), 'utf8'));
const demo = await runAudit(demoManifest, [demoFile], adapter);
const issues = page => page.issues.map(i => i.code).sort();
test('GTIN normalization preserves the complete approved value', () => { assert.equal(normalizeGtin('9506000134352'), A); assert.equal(normalizeGtin('036000291452'), '00036000291452'); assert.equal(normalizeGtin('96385074'), '00000096385074'); });
test('Invalid check digits and scientific notation are rejected', () => { for (const v of ['09506000134353', '9.506e12', '950600013435', 9506000134352]) assert.throws(() => normalizeGtin(v)); });
test('Quoted CSV values and a BOM are read', () => { assert.equal(parseManifest('\uFEFF' + csv().replace('SKU-A', '"SKU, A"'))[0].sku, 'SKU, A'); });
test('Malformed CSV is rejected instead of shifting product columns', () => { for (const s of [csv().replace('SKU-A', '"unclosed'), csv().replace('SKU-A', '"quoted"extra'), csv().replace('SKU-A,', 'SKU-A,extra,')]) assert.throws(() => parseManifest(s)); });
test('Required columns, duplicate columns and unknown columns are checked', () => { for (const s of [csv().replace('sku,',''), csv().replace('sku,','sku,sku,'), csv().replace('sku,','product,')]) assert.throws(() => parseManifest(s)); });
test('Repeated file/page rows cannot silently replace approved products', () => { assert.throws(() => parseManifest(csv() + csv().split('\n')[1])); });
test('Unsafe filenames, page numbers and empty SKUs are rejected', () => { for (const s of [csv('../proof.png'), csv().replace(',1,SKU-A', ',0,SKU-A'), csv().replace(',1,SKU-A', ',201,SKU-A'), csv().replace('SKU-A','')]) assert.throws(() => parseManifest(s)); });
test('Counts must be bounded integers and cannot both be zero', () => { for (const [a,b] of [[0,0],[17,1],[-1,1],[1.5,1]]) assert.throws(() => parseManifest(csv('x.png',A,a,b))); });
test('Digital Link URL qualifiers retain the product GTIN', () => { assert.equal(digitalLink('https://id.example.com/stem/01/'+A+'/10/BATCH?17=280101').gtin, A); });
test('Ambiguous, compressed, credentialed and invalid links require review', () => { for (const s of ['https://x/abc','https://x/01/'+A+'/01/'+B,'https://x/01/'+A+'?01='+B,'https://u:p@x/01/'+A,'https://x/01/'+A+'#x','https://x/01/09506000134353','javascript:alert(1)']) assert.throws(() => digitalLink(s)); });
test('Unexpected barcode formats and inconsistent digit lengths do not pass', () => { assert.equal(classify({format:'Code128',text:A}).kind,'unsupported'); assert.equal(classify({format:'EAN8',text:A}).kind,'unsupported'); assert.equal(classify({format:'EAN13',text:A.slice(1),decodeError:'checksum'}).kind,'unsupported'); });
test('Real seven-page PDF produces two matches and six review items', () => assert.deepEqual(demo.report.summary,{pages:8,suppliedPages:7,matched:2,review:6}));
test('Real decoded PDF values match independently generated truth', () => { demo.report.pages.slice(0,7).forEach((p,i) => assert.deepEqual(p.codes.map(c=>c.text).sort(), truth.pdf_source_pages[i].texts)); });
test('Conflicting linear and Digital Link products are flagged', () => assert.deepEqual(issues(demo.report.pages[1]),['CODE_DISAGREEMENT','WRONG_PRODUCT']));
test('Two agreeing but wrong-product codes still fail approval', () => { const p=demo.report.pages[2]; assert.equal(p.status,'review'); assert.equal(p.issues.filter(i=>i.code==='WRONG_PRODUCT').length,2); assert.ok(!issues(p).includes('CODE_DISAGREEMENT')); });
test('A missing QR does not pass when the linear code is correct', () => assert.deepEqual(issues(demo.report.pages[3]),['LINK_COUNT']));
test('Both copies of identical artwork are flagged', () => { for(const i of [2,4]) assert.ok(issues(demo.report.pages[i]).includes('DUPLICATE_ARTWORK')); });
test('A rotated proof is actually decoded and matched', () => { assert.equal(demo.report.pages[5].status,'matched'); assert.equal(demo.report.pages[5].codes.length,2); });
test('An unlisted page and a missing approved page require review', () => { assert.deepEqual(issues(demo.report.pages[6]),['UNLISTED_PAGE']); assert.deepEqual(issues(demo.report.pages[7]),['MISSING_PAGE']); });
test('Every supplied page gets an annotated PNG preview', () => { assert.equal(demo.previews.size,7); for(const png of demo.previews.values()) assert.equal(Buffer.from(png.subarray(0,8)).toString('hex'),'89504e470d0a1a0a'); });
for (const [name,gtin,linear,link,status] of [['clean.png',A,1,1,'matched'],['clean.jpg',A,1,1,'matched'],['rotated.png',B,1,1,'matched'],['ean8.png','96385074',1,0,'matched'],['upca.png','036000291452',1,0,'matched'],['datamatrix.png',A,0,1,'matched'],['unknown.png',A,1,1,'review'],['damaged.png',A,1,1,'review'],['wrong-host.png',A,1,1,'review']]) {
  test('Actual image decoding: '+name, async () => { const f=await file('fixtures/'+name), r=await runAudit(csv(name,gtin,linear,link),[f],adapter); assert.equal(r.report.pages[0].status,status); const canonical=s=>/^\d+$/.test(s)?normalizeGtin(s):s; assert.deepEqual(r.report.pages[0].codes.map(c=>canonical(c.text)).sort(),truth.images[name].map(canonical).sort()); });
}
test('Input SHA256 values use exact original bytes', () => { assert.equal(demo.report.inputs[1].sha256,createHash('sha256').update(demoFile.bytes).digest('hex')); });
test('A decoder failure yields a page error, never a match', async () => { const r=await runAudit(csv('clean.png'),[await file('fixtures/clean.png')],{...adapter,decode:async()=>{throw Error('Decoder unavailable');}}); assert.ok(issues(r.report.pages[0]).includes('PAGE_ERROR')); assert.equal(r.report.pages[0].status,'review'); });
test('Case-insensitive filename collisions and unsupported files are rejected', () => { assert.throws(()=>checkInputs([{name:'a.png',bytes:new Uint8Array(1)},{name:'A.PNG',bytes:new Uint8Array(1)}])); assert.throws(()=>checkInputs([{name:'a.svg',bytes:new Uint8Array(1)}])); });
test('Corrupt PDFs stop the batch with a named error', async () => { await assert.rejects(()=>runAudit(csv('bad.pdf'),[{name:'bad.pdf',bytes:new TextEncoder().encode('not a PDF')}],adapter),/Cannot open bad.pdf/); });
test('Page and byte limits are enforced before a success report', async () => { await assert.rejects(()=>runAudit(csv('x.pdf'),[{name:'x.pdf',bytes:new Uint8Array(1)}],{...adapter,open:async()=>({count:LIMITS.pages+1,close:async()=>{}})}),/200/); assert.throws(()=>checkInputs([{name:'x.png',bytes:{length:LIMITS.fileBytes+1}}])); });
test('Exported HTML escapes product text and CSV blocks formulas', () => { const r=structuredClone(demo.report);r.pages[0].sku='<img src=x onerror=alert(1)>'; assert.ok(packetFiles(r,demo.previews).find(f=>f.name==='review.html').text.includes('&lt;img')); r.pages[0].sku='=HYPERLINK("x")'; assert.ok(reportCsv(r).includes('"\'=HYPERLINK')); assert.equal(escapeHtml('<>&'),'&lt;&gt;&amp;'); });
test('Packet has all reports and seven previews in a complete ZIP', () => { assert.equal(packetFiles(demo.report,demo.previews).length,11); const z=packetZip(demo.report,demo.previews); assert.equal(new DataView(z.buffer).getUint32(0,true),0x04034b50); assert.equal(new DataView(z.buffer).getUint16(z.length-12,true),11); });
test('CLI protects existing output folders and offers a CI review exit code', async () => { const folder=await mkdtemp(join(tmpdir(),'artwork-audit-')); try { const out=join(folder,'result'),cli=new URL('../bin/audit.mjs',import.meta.url); const argv=[cli.pathname.replace(/^\/(\w:)/,'$1'),'--manifest','docs/samples/approved.csv','--artwork','docs/samples/proofs.pdf','--out',out,'--fail-on-review']; const {fileURLToPath}=await import('node:url');argv[0]=fileURLToPath(cli);let r=spawnSync(process.execPath,argv,{encoding:'utf8'});assert.equal(r.status,2,r.stderr);const before=await readFile(join(out,'report.json'));r=spawnSync(process.execPath,argv,{encoding:'utf8'});assert.equal(r.status,1);assert.deepEqual(await readFile(join(out,'report.json')),before);assert.ok((await stat(join(out,'artwork-review.zip'))).size>0); } finally { await rm(folder,{recursive:true,force:true}); } });
